// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://melbptgutajptxhpjeuv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1lbGJwdGd1dGFqcHR4aHBqZXV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzNzg2NDAsImV4cCI6MjA4NTk1NDY0MH0.YVCUKgmavn9CNiXctYvxLiVMh9KDuKjv_t9wZB1K_Ms";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});